/*Crea tablas a partir de los ficheros .csv para procesar los datos, 
  estas tablas serán eliminadas posteriormente.
   
  Observaciones: 
  - el fichero Rendimiento2021.csv contiene errores. Salto de línea que no deberían estar
    en las siguientes líneas: 4264 y 4523.
     
*/

-- Tabla Oferta
drop table if exists Oferta;
create table Oferta (CURSO_ACADEMICO integer, ESTUDIO varchar(200), LOCALIDAD varchar(200),
	CENTRO varchar(200), TIPO_CENTRO varchar(200), TIPO_ESTUDIO varchar(200),
	PLAZAS_OFERTADAS integer,
	PLAZAS_MATRICULADAS integer, PLAZAS_SOLICITADAS integer, INDICE_OCUPACION numeric(5,2),
	FECHA_ACTUALIZACION varchar(200));

copy Oferta (CURSO_ACADEMICO, ESTUDIO, LOCALIDAD, CENTRO, TIPO_CENTRO, TIPO_ESTUDIO,
	PLAZAS_OFERTADAS, PLAZAS_MATRICULADAS, PLAZAS_SOLICITADAS, INDICE_OCUPACION,
	FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Oferta2019.csv'
	delimiter ';' csv header;

copy Oferta (CURSO_ACADEMICO, ESTUDIO, LOCALIDAD, CENTRO, TIPO_CENTRO, TIPO_ESTUDIO,
	PLAZAS_OFERTADAS, PLAZAS_MATRICULADAS, PLAZAS_SOLICITADAS, INDICE_OCUPACION,
	FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Oferta2020.csv'
	delimiter ';' csv header;

copy Oferta (CURSO_ACADEMICO, ESTUDIO, LOCALIDAD, CENTRO, TIPO_CENTRO, TIPO_ESTUDIO,
	PLAZAS_OFERTADAS, PLAZAS_MATRICULADAS, PLAZAS_SOLICITADAS, INDICE_OCUPACION,
	FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Oferta2021.csv'
	delimiter ';' csv header;

-- Tabla Resultados
drop table if exists Resultados;
create table Resultados (CURSO_ACADEMICO integer, CENTRO varchar(200), ESTUDIO varchar(200),
	TIPO_ESTUDIO varchar(200), ALUMNOS_MATRICULADOS integer, ALUMNOS_NUEVO_INGRESO integer, 
	PLAZAS_OFERTADAS integer, ALUMNOS_GRADUADOS integer, ALUMNOS_ADAPTA_GRADO_MATRI integer,
	ALUMNOS_ADAPTA_GRADO_MATRI_NI integer, ALUMNOS_ADAPTA_GRADO_TITULADO integer,
	ALUMNOS_CON_RECONOCIMIENTO integer, ALUMNOS_MOVILIDAD_ENTRADA integer,
	ALUMNOS_MOVILIDAD_SALIDA integer, CREDITOS_MATRICULADOS decimal(7,2),
	CREDITOS_RECONOCIDOS decimal(7,2), DURACION_MEDIA_GRADUADOS decimal(6,2), 
	TASA_EXITO decimal(6,2), TASA_RENDIMIENTO decimal(6,2), TASA_EFICIENCIA decimal(6,2),
	TASA_ABANDONO decimal(6,2), TASA_GRADUACION decimal(6,2),
	FECHA_ACTUALIZACION varchar(200));

copy Resultados (CURSO_ACADEMICO, CENTRO, ESTUDIO, TIPO_ESTUDIO, ALUMNOS_MATRICULADOS,
	ALUMNOS_NUEVO_INGRESO, PLAZAS_OFERTADAS, ALUMNOS_GRADUADOS, ALUMNOS_ADAPTA_GRADO_MATRI,
	ALUMNOS_ADAPTA_GRADO_MATRI_NI, ALUMNOS_ADAPTA_GRADO_TITULADO,
	ALUMNOS_CON_RECONOCIMIENTO, ALUMNOS_MOVILIDAD_ENTRADA, ALUMNOS_MOVILIDAD_SALIDA,
	CREDITOS_MATRICULADOS, CREDITOS_RECONOCIDOS, DURACION_MEDIA_GRADUADOS, TASA_EXITO,
	TASA_RENDIMIENTO, TASA_EFICIENCIA, TASA_ABANDONO, TASA_GRADUACION, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Resultados2019.csv' 
	delimiter ';' csv header;

copy Resultados (CURSO_ACADEMICO, CENTRO, ESTUDIO, TIPO_ESTUDIO, ALUMNOS_MATRICULADOS,
	ALUMNOS_NUEVO_INGRESO, PLAZAS_OFERTADAS, ALUMNOS_GRADUADOS, ALUMNOS_ADAPTA_GRADO_MATRI,
	ALUMNOS_ADAPTA_GRADO_MATRI_NI, ALUMNOS_ADAPTA_GRADO_TITULADO,
	ALUMNOS_CON_RECONOCIMIENTO, ALUMNOS_MOVILIDAD_ENTRADA, ALUMNOS_MOVILIDAD_SALIDA,
	CREDITOS_MATRICULADOS, CREDITOS_RECONOCIDOS, DURACION_MEDIA_GRADUADOS, TASA_EXITO,
	TASA_RENDIMIENTO, TASA_EFICIENCIA, TASA_ABANDONO, TASA_GRADUACION, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Resultados2020.csv' 
	delimiter ';' csv header;

copy Resultados (CURSO_ACADEMICO, CENTRO, ESTUDIO, TIPO_ESTUDIO, ALUMNOS_MATRICULADOS,
	ALUMNOS_NUEVO_INGRESO, PLAZAS_OFERTADAS, ALUMNOS_GRADUADOS, ALUMNOS_ADAPTA_GRADO_MATRI,
	ALUMNOS_ADAPTA_GRADO_MATRI_NI, ALUMNOS_ADAPTA_GRADO_TITULADO,
	ALUMNOS_CON_RECONOCIMIENTO, ALUMNOS_MOVILIDAD_ENTRADA, ALUMNOS_MOVILIDAD_SALIDA,
	CREDITOS_MATRICULADOS, CREDITOS_RECONOCIDOS,
	DURACION_MEDIA_GRADUADOS, TASA_EXITO, TASA_RENDIMIENTO, TASA_EFICIENCIA, TASA_ABANDONO,
	TASA_GRADUACION, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Resultados2021.csv' 
	delimiter ';' csv header;

-- Tabla Notas
drop table if exists Notas;
create table Notas (CURSO_ACADEMICO integer, ESTUDIO varchar(200), LOCALIDAD varchar(200),
	CENTRO varchar(200), PRELA_CONVO_NOTA_DEF decimal(5,3), 
	NOTA_CORTE_DEFINITIVA_JULIO decimal(5,3),
	NOTA_CORTE_DEFINITIVA_SEPTIEMBRE decimal(5,3), FECHA_ACTUALIZACION varchar(200));

copy Notas (CURSO_ACADEMICO, ESTUDIO, LOCALIDAD, CENTRO, PRELA_CONVO_NOTA_DEF,
	NOTA_CORTE_DEFINITIVA_JULIO, NOTA_CORTE_DEFINITIVA_SEPTIEMBRE, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Notas2019.csv'
	delimiter ';' csv header;

copy Notas (CURSO_ACADEMICO, ESTUDIO, LOCALIDAD, CENTRO, PRELA_CONVO_NOTA_DEF,
	NOTA_CORTE_DEFINITIVA_JULIO, NOTA_CORTE_DEFINITIVA_SEPTIEMBRE, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Notas2020.csv'
	delimiter ';' csv header;

copy Notas (CURSO_ACADEMICO, ESTUDIO, LOCALIDAD, CENTRO, PRELA_CONVO_NOTA_DEF,
	NOTA_CORTE_DEFINITIVA_JULIO, NOTA_CORTE_DEFINITIVA_SEPTIEMBRE, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Notas2021.csv'
	delimiter ';' csv header;

-- Tabla Movilidad
drop table if exists Movilidad;
create table Movilidad (CURSO_ACADEMICO integer, NOMBRE_PROGRAMA_MOVILIDAD varchar(200),
	NOMBRE_AREA_ESTUDIOS_MOV varchar(200), CENTRO varchar(200), IN_OUT varchar(200), 
	NOMBRE_IDIOMA_NIVEL_MOVILIDAD varchar(200), PAIS_UNIVERSIDAD_ACUERDO varchar(200),
	UNIVERSIDAD_ACUERDO varchar(200), PLAZAS_OFERTADAS_ALUMNOS integer,
	PLAZAS_ASIGNADAS_ALUMNOS_OUT integer, FECHA_ACTUALIZACION varchar(200));

copy Movilidad (CURSO_ACADEMICO, NOMBRE_PROGRAMA_MOVILIDAD, NOMBRE_AREA_ESTUDIOS_MOV, CENTRO,
	IN_OUT, NOMBRE_IDIOMA_NIVEL_MOVILIDAD, PAIS_UNIVERSIDAD_ACUERDO, UNIVERSIDAD_ACUERDO,
	PLAZAS_OFERTADAS_ALUMNOS, PLAZAS_ASIGNADAS_ALUMNOS_OUT, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Movilidad2019.csv' 
	delimiter ';' csv header;

copy Movilidad (CURSO_ACADEMICO, NOMBRE_PROGRAMA_MOVILIDAD, NOMBRE_AREA_ESTUDIOS_MOV, CENTRO,
	IN_OUT, NOMBRE_IDIOMA_NIVEL_MOVILIDAD, PAIS_UNIVERSIDAD_ACUERDO, UNIVERSIDAD_ACUERDO,
	PLAZAS_OFERTADAS_ALUMNOS, PLAZAS_ASIGNADAS_ALUMNOS_OUT, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Movilidad2020.csv' 
	delimiter ';' csv header;

copy Movilidad (CURSO_ACADEMICO, NOMBRE_PROGRAMA_MOVILIDAD, NOMBRE_AREA_ESTUDIOS_MOV, CENTRO,
	IN_OUT, NOMBRE_IDIOMA_NIVEL_MOVILIDAD, PAIS_UNIVERSIDAD_ACUERDO, UNIVERSIDAD_ACUERDO,
	PLAZAS_OFERTADAS_ALUMNOS, PLAZAS_ASIGNADAS_ALUMNOS_OUT, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Movilidad2021.csv' 
	delimiter ';' csv header;

-- Tabla Egresados
drop table if exists Egresados;
create table Egresados (CURSO_ACADEMICO integer, LOCALIDAD varchar(200), ESTUDIO varchar(200),
	TIPO_ESTUDIO varchar(200), TIPO_EGRESO varchar(200), SEXO varchar(200),
	ALUMNOS_GRADUADOS integer, ALUMNOS_INTERRUMPEN_ESTUDIOS integer,
	ALUMNOS_INTERRUMPEN_EST_ANO1 integer, ALUMNOS_TRASLADAN_OTRA_UNIV integer,
	DURACION_MEDIA_GRADUADOS decimal(5,2), TASA_EFICIENCIA decimal(5,2),
	FECHA_ACTUALIZACION varchar(200));

copy Egresados (CURSO_ACADEMICO, LOCALIDAD, ESTUDIO, TIPO_ESTUDIO, TIPO_EGRESO, SEXO,
	ALUMNOS_GRADUADOS, ALUMNOS_INTERRUMPEN_ESTUDIOS, ALUMNOS_INTERRUMPEN_EST_ANO1,
	ALUMNOS_TRASLADAN_OTRA_UNIV, DURACION_MEDIA_GRADUADOS, TASA_EFICIENCIA,
	FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Egresados2019.csv' 
	delimiter ';' csv header;

copy Egresados (CURSO_ACADEMICO, LOCALIDAD, ESTUDIO, TIPO_ESTUDIO, TIPO_EGRESO, SEXO,
	ALUMNOS_GRADUADOS, ALUMNOS_INTERRUMPEN_ESTUDIOS, ALUMNOS_INTERRUMPEN_EST_ANO1,
	ALUMNOS_TRASLADAN_OTRA_UNIV, DURACION_MEDIA_GRADUADOS, TASA_EFICIENCIA,
	FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Egresados2020.csv' 
	delimiter ';' csv header;

copy Egresados (CURSO_ACADEMICO, LOCALIDAD, ESTUDIO, TIPO_ESTUDIO, TIPO_EGRESO, SEXO,
	ALUMNOS_GRADUADOS, ALUMNOS_INTERRUMPEN_ESTUDIOS, ALUMNOS_INTERRUMPEN_EST_ANO1,
	ALUMNOS_TRASLADAN_OTRA_UNIV, DURACION_MEDIA_GRADUADOS, TASA_EFICIENCIA,
	FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Egresados2021.csv' 
	delimiter ';' csv header;

-- Tabla Rendimiento
drop table if exists Rendimiento;
create table Rendimiento (CURSO_ACADEMICO integer, TIPO_ESTUDIO varchar(200), 
	ESTUDIO varchar(200), LOCALIDAD varchar(200), CENTRO varchar(200), 
	ASIGNATURA varchar(200), TIPO_ASIGNATURA varchar(200), CLASE_ASIGNATURA varchar(200),
	TASA_EXITO decimal(5,2), TASA_RENDIMIENTO decimal(5,2), TASA_EVALUACION decimal(5,2),
	ALUMNOS_EVALUADOS integer, ALUMNOS_SUPERADOS integer, ALUMNOS_PRESENTADOS integer,
	MEDIA_CONVOCATORIAS_CONSUMIDAS decimal(5,2), FECHA_ACTUALIZACION varchar(200));

copy Rendimiento (CURSO_ACADEMICO, TIPO_ESTUDIO, ESTUDIO, LOCALIDAD, CENTRO, ASIGNATURA,
	TIPO_ASIGNATURA, CLASE_ASIGNATURA, TASA_EXITO, TASA_RENDIMIENTO, TASA_EVALUACION,
	ALUMNOS_EVALUADOS, ALUMNOS_SUPERADOS, ALUMNOS_PRESENTADOS,
	MEDIA_CONVOCATORIAS_CONSUMIDAS, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Rendimiento2019.csv' 
	delimiter ';' csv header;

copy Rendimiento (CURSO_ACADEMICO, TIPO_ESTUDIO, ESTUDIO, LOCALIDAD, CENTRO, ASIGNATURA,
	TIPO_ASIGNATURA, CLASE_ASIGNATURA, TASA_EXITO, TASA_RENDIMIENTO, TASA_EVALUACION,
	ALUMNOS_EVALUADOS, ALUMNOS_SUPERADOS, ALUMNOS_PRESENTADOS,
	MEDIA_CONVOCATORIAS_CONSUMIDAS, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Rendimiento2020.csv'
	delimiter ';' csv header;

copy Rendimiento (CURSO_ACADEMICO, TIPO_ESTUDIO, ESTUDIO, LOCALIDAD, CENTRO, ASIGNATURA,
	TIPO_ASIGNATURA, CLASE_ASIGNATURA, TASA_EXITO, TASA_RENDIMIENTO, TASA_EVALUACION,
	ALUMNOS_EVALUADOS, ALUMNOS_SUPERADOS, ALUMNOS_PRESENTADOS,
	MEDIA_CONVOCATORIAS_CONSUMIDAS, FECHA_ACTUALIZACION) 
	from '/home/bowy/uni/bd2/repositorio/bd2/practica1/postgresql/Datos/Rendimiento2021.csv' 
	delimiter ';' csv header;
